# Uncomment the next line to define a global platform for your project
platform :ios, '15.1'

# CocoaPods analytics sends network stats synchronously affecting
# bootup times, so we opt out of it here.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'LocalAI',
  'Debug' => :debug,
  'Release' => :release

def node_require(script)
  require Pod::Executable.execute_command('node', ['-e',
    "process.stdout.write(require.resolve('#{script}'))",
  ], true)
end

node_require('react-native/scripts/react_native_pods.rb')

prepare_react_native_project!

target 'LocalAI' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => true,
    :fabric_enabled => false,
    # Enables Flipper.
    # Note that if you have use_frameworks! enabled, Flipper will not work
    # and you should disable the next line.
    :flipper_configuration => FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # llama.rn – on-device LLM inference with Metal GPU support
  pod 'llama.rn', :path => '../node_modules/llama.rn'

  target 'LocalAITests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
    )

    # Enable Metal GPU acceleration for llama.rn
    installer.pods_project.targets.each do |target|
      if target.name == 'llama.rn'
        target.build_configurations.each do |config|
          config.build_settings['OTHER_CPLUSPLUSFLAGS'] = '$(inherited) -DGGML_USE_METAL=1'
          config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = '$(inherited) GGML_USE_METAL=1'
        end
      end
    end
  end
end
